## Pengenalan Data Frame

### 1. Pandas

In [1]:
# Import modul
import pandas as pd

In [4]:
# Membuat Data Frame
list_buah = ['Mangga', 'Nanas', 'Anggur', 'Jeruk']
df = pd.DataFrame(list_buah)
df

0
0  Mangga
1   Nanas
2  Anggur
3   Jeruk

In [6]:
# Membuat Data Frame menggunakan list dan fungsi zip
list_buah = ['Mangga', 'Nanas', 'Anggur', 'Jeruk']
list_banyak = [10, 20, 40, 30]

df = pd.DataFrame(list(zip(list_buah, list_banyak)),
                  columns = ['Nama Buah', 'Banyak Buah'])
df

Nama Buah  Banyak Buah
0    Mangga           10
1     Nanas           20
2    Anggur           40
3     Jeruk           30

In [9]:
# Membuat Data Frame menggunakan List Multidimensi
list = [['Bejo', 25], ['Arif', 19], ['Anang', 45], ['Angga', 15]]
df = pd.DataFrame(list, columns = ['Nama', 'Usia'])
df

Nama  Usia
0   Bejo    25
1   Arif    19
2  Anang    45
3  Angga    15

In [11]:
# Membuat Data Frame menggunakan dictionary
Laptop = {'Type Laptop' : ['ASUS', 'Hp', 'Lenovo', 'Samsung', 'MacbookAir'], 
         'Harga (juta)' : [12, 5, 9, 10, 25]}
df = pd.DataFrame(Laptop)
df

Type Laptop  Harga (juta)
0        ASUS            12
1          Hp             5
2      Lenovo             9
3     Samsung            10
4  MacbookAir            25

In [17]:
# Membuat Data Frame dari import Data

## Data CSV
data = pd.read_csv('DataPenjualan.csv')
data

id_record     tanggal  id_outlet  id_produk  produk_terjual
0             1  01/10/2022          1          1              85
1             2  01/10/2022          1          2             110
2             3  01/10/2022          1          3             116
3             4  01/10/2022          1          4              72
4             5  01/10/2022          1          5              78
...         ...         ...        ...        ...             ...
1855       1856  31/10/2022          6          6              86
1856       1857  31/10/2022          6          7              74
1857       1858  31/10/2022          6          8              67
1858       1859  31/10/2022          6          9              57
1859       1860  31/10/2022          6         10              92

[1860 rows x 5 columns]

In [18]:
data = pd.read_csv('DataPenjualan.csv')
data.head(10)

id_record     tanggal  id_outlet  id_produk  produk_terjual
0          1  01/10/2022          1          1              85
1          2  01/10/2022          1          2             110
2          3  01/10/2022          1          3             116
3          4  01/10/2022          1          4              72
4          5  01/10/2022          1          5              78
5          6  01/10/2022          1          6             101
6          7  01/10/2022          1          7              91
7          8  01/10/2022          1          8              82
8          9  01/10/2022          1          9             106
9         10  01/10/2022          1         10              53

In [19]:
## Data Excel
data = pd.read_excel('BangunLima.xlsx')
data

Ca  HCO3  Mg  SO4  NO2
0    1     2   1   20    2
1    2     3   2   19    3
2    3     4   3   18    4
3    4     5   4   17    5
4    5     7   5   16    7
5    6     3   6   15    3
6    7     3   7   14    3
7    8     4   8   13    4
8    9     7   9   12    7
9   10     8  10   11    8
10  10     3  11   10    3
11   9     5  12    9    5
12   8     6  13    8    6
13   7     1  14    7    1
14   6     3  15    6    3
15   5     4  16    5    4
16   4     9  17    4    9
17   3     4  18    3    4
18   2     6  19    2    6
19   1     2  20    1    2

### 2. Numpy

In [36]:
# Import modul
import numpy as np

In [21]:
# Membuat Array numpy
list = [1,2,3,4,5,6,7,8,9,10]
arr_list = np.array([list])
arr_list

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [23]:
# Fungsi didalam numpy

##zeros() -> nilai 0
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
##ones() -> nilai 1
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
##arange() -> (start, stop, step/loncat berapa)
print(np.arange(6, 20, 4))

[ 6 10 14 18]


In [33]:
##linspace() -> (start, stop, number)
print(np.linspace(1, 10, 4))

[ 1.  4.  7. 10.]


In [39]:
##logspace() -> (start, stop, number)
print(np.logspace(1, 10, 2))

[1.e+01 1.e+10]


In [38]:
##full()
print(np.full((2,5), 4))

[[4 4 4 4 4]
 [4 4 4 4 4]]


In [44]:
##full_like()
A = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(A)

print(np.full_like(A, 4))

[[ 1  2  3  4  5  6  7  8  9 10]]
[[4 4 4 4 4 4 4 4 4 4]]


In [46]:
##random() -> jika di run hasil nya akan beda2
print(np.random.randint(-4,8, size = (3,3)))

[[ 1  7 -1]
 [ 6 -2 -1]
 [-3  7  2]]


In [47]:
##identity()
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [54]:
##repeat() -> Membuat matriks dengan perulangan array(kolom), axis = 1 (perulangan baris)
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
##mengetahui dimensi arrya
A = np.array([1,2,3,4,5,6,7,8,9,10], dtype = 'int32')
print(A)

print("Dimnsi array A : ", A.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimnsi array A :  1


In [58]:
##mengetahui ukuran array
A = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(A)

print("Dimnsi array A : ", A.shape)

[[ 1  2  3  4  5  6  7  8  9 10]]
Dimnsi array A :  (1, 10)


In [59]:
A.size

10

### Indexing dan Slicing

In [63]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
print(A[0])
print(A[0:5])

1
[1 2 3 4 5]


In [64]:
A = np.array([[1,2,3,4,5], [2,4,5,6,7]])
print(A)
print(A[4:5])

[[1 2 3 4 5]
 [2 4 5 6 7]]
[]
